name: OpenMRS __Elite Ass__ Documentation
title: WriteAdapt - For People Who Love Content
org: OpenMRS
author: Paul Biondich
author_url: https://github.com/docpaul
base_url: ''
ctx_path: ''
interpolate: false
haml:
  :ugly: true
asciidoctor:
  :safe: safe
  :attributes:
    sitename: WriteAdapt
    base_url: ''
    ctx_path: ''
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    icons: font
